spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/main-db
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO
        transaction:
          interceptor: DEBUG
          nodeValue: INFO
    hibernate:
      SQL: DEBUG

server:
  port: 8080
